# Generated by Django 5.2.1 on 2025-07-08 17:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("cover", models.ImageField(blank=True, upload_to="covers/")),
                (
                    "book_format",
                    models.CharField(
                        choices=[("FB2", "FB2"), ("EPUB", "EPUB")], max_length=4
                    ),
                ),
                ("file", models.FileField(blank=True, null=True, upload_to="books/")),
                ("authors", models.TextField(blank=True)),
                ("genres", models.TextField(blank=True)),
                ("language", models.CharField(default="en", max_length=10)),
                ("file_size", models.PositiveIntegerField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="DictionaryEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=50)),
                ("translation", models.CharField(max_length=50)),
                ("transcription", models.CharField(blank=True, max_length=50)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("ru", "Russian"),
                            ("en", "English"),
                            ("es", "Spanish"),
                            ("fr", "French"),
                            ("de", "German"),
                            ("zh", "Chinese"),
                            ("ja", "Japanese"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dictionary_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FlashCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=50)),
                ("translation", models.CharField(max_length=50)),
                ("example", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, upload_to="flashcard_images/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TL", "To Learn"),
                            ("KN", "Known"),
                            ("LD", "Learned"),
                        ],
                        default="TL",
                        max_length=2,
                    ),
                ),
                ("ease_factor", models.FloatField(default=2.5)),
                ("interval", models.IntegerField(default=1)),
                ("repetitions", models.IntegerField(default=0)),
                (
                    "next_review",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("last_reviewed", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flashcards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("assistant", "Assistant")],
                        max_length=10,
                    ),
                ),
                ("content", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="reader.conversation",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "native_language",
                    models.CharField(
                        choices=[
                            ("ru", "Russian"),
                            ("en", "English"),
                            ("es", "Spanish"),
                            ("fr", "French"),
                            ("de", "German"),
                            ("zh", "Chinese"),
                            ("ja", "Japanese"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "language_to_learn",
                    models.CharField(
                        choices=[
                            ("ru", "Russian"),
                            ("en", "English"),
                            ("es", "Spanish"),
                            ("fr", "French"),
                            ("de", "German"),
                            ("zh", "Chinese"),
                            ("ja", "Japanese"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "current_level",
                    models.CharField(
                        choices=[
                            ("A1", "Beginner"),
                            ("A2", "Elementary"),
                            ("B1", "Intermediate"),
                            ("B2", "Upper Intermediate"),
                            ("C1", "Advanced"),
                            ("C2", "Proficient"),
                        ],
                        help_text="CEFR level, e.g. A1, B2",
                        max_length=10,
                    ),
                ),
                (
                    "google_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("avatar_url", models.ImageField(blank=True, null=True, upload_to="")),
                ("is_google_user", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("content", models.TextField()),
                ("order", models.PositiveIntegerField()),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="reader.book",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("book", "order")},
            },
        ),
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_text",
                    models.TextField(
                        max_length=5000,
                        validators=[django.core.validators.MinLengthValidator(1)],
                        verbose_name="Исходный текст",
                    ),
                ),
                (
                    "translated_text",
                    models.TextField(verbose_name="Переведенный текст"),
                ),
                (
                    "source_language",
                    models.CharField(
                        choices=[
                            ("ru", "Русский"),
                            ("en", "Английский"),
                            ("de", "Немецкий"),
                            ("fr", "Французский"),
                            ("es", "Испанский"),
                            ("it", "Итальянский"),
                            ("pt", "Португальский"),
                            ("pl", "Польский"),
                            ("nl", "Голландский"),
                            ("ja", "Японский"),
                            ("zh", "Китайский"),
                            ("ko", "Корейский"),
                            ("ar", "Арабский"),
                            ("hi", "Хинди"),
                            ("tr", "Турецкий"),
                            ("uk", "Украинский"),
                            ("bg", "Болгарский"),
                            ("cs", "Чешский"),
                            ("auto", "Автоопределение"),
                        ],
                        default="auto",
                        max_length=10,
                        verbose_name="Исходный язык",
                    ),
                ),
                (
                    "target_language",
                    models.CharField(
                        choices=[
                            ("ru", "Русский"),
                            ("en", "Английский"),
                            ("de", "Немецкий"),
                            ("fr", "Французский"),
                            ("es", "Испанский"),
                            ("it", "Итальянский"),
                            ("pt", "Португальский"),
                            ("pl", "Польский"),
                            ("nl", "Голландский"),
                            ("ja", "Японский"),
                            ("zh", "Китайский"),
                            ("ko", "Корейский"),
                            ("ar", "Арабский"),
                            ("hi", "Хинди"),
                            ("tr", "Турецкий"),
                            ("uk", "Украинский"),
                            ("bg", "Болгарский"),
                            ("cs", "Чешский"),
                            ("auto", "Автоопределение"),
                        ],
                        default="ru",
                        max_length=10,
                        verbose_name="Целевой язык",
                    ),
                ),
                (
                    "translator_service",
                    models.CharField(
                        choices=[
                            ("deepl", "DeepL"),
                            ("google", "Google Translate"),
                            ("contextil", "Contextil"),
                        ],
                        max_length=20,
                        verbose_name="Сервис перевода",
                    ),
                ),
                (
                    "context",
                    models.TextField(
                        blank=True, max_length=1000, null=True, verbose_name="Контекст"
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        blank=True,
                        help_text="Значение от 0 до 1",
                        null=True,
                        verbose_name="Уверенность перевода",
                    ),
                ),
                (
                    "processing_time_ms",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Время обработки (мс)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Перевод",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="reader_tran_user_id_5564da_idx",
                    ),
                    models.Index(
                        fields=["user", "target_language"],
                        name="reader_tran_user_id_796778_idx",
                    ),
                    models.Index(
                        fields=["user", "translator_service"],
                        name="reader_tran_user_id_939609_idx",
                    ),
                    models.Index(
                        fields=[
                            "original_text",
                            "target_language",
                            "translator_service",
                        ],
                        name="reader_tran_origina_8549e1_idx",
                    ),
                ],
                "unique_together": {
                    ("user", "original_text", "target_language", "translator_service")
                },
            },
        ),
    ]
