# Generated by Django 5.2.1 on 2025-07-30 14:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reader", "0003_alter_book_language"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="translation",
            name="reader_tran_origina_8549e1_idx",
        ),
        migrations.AlterUniqueTogether(
            name="translation",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="translation",
            name="source_language",
            field=models.CharField(
                choices=[
                    ("ru", "Русский"),
                    ("en", "Английский"),
                    ("de", "Немецкий"),
                    ("fr", "Французский"),
                    ("es", "Испанский"),
                    ("it", "Итальянский"),
                    ("pt", "Португальский"),
                    ("pl", "Польский"),
                    ("nl", "Голландский"),
                    ("ja", "Японский"),
                    ("zh", "Китайский"),
                    ("ko", "Корейский"),
                    ("ar", "Арабский"),
                    ("hi", "Хинди"),
                    ("tr", "Турецкий"),
                    ("uk", "Украинский"),
                    ("bg", "Болгарский"),
                    ("cs", "Чешский"),
                ],
                max_length=10,
                verbose_name="Исходный язык",
            ),
        ),
        migrations.AlterField(
            model_name="translation",
            name="target_language",
            field=models.CharField(
                choices=[
                    ("ru", "Русский"),
                    ("en", "Английский"),
                    ("de", "Немецкий"),
                    ("fr", "Французский"),
                    ("es", "Испанский"),
                    ("it", "Итальянский"),
                    ("pt", "Португальский"),
                    ("pl", "Польский"),
                    ("nl", "Голландский"),
                    ("ja", "Японский"),
                    ("zh", "Китайский"),
                    ("ko", "Корейский"),
                    ("ar", "Арабский"),
                    ("hi", "Хинди"),
                    ("tr", "Турецкий"),
                    ("uk", "Украинский"),
                    ("bg", "Болгарский"),
                    ("cs", "Чешский"),
                ],
                max_length=10,
                verbose_name="Целевой язык",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="translation",
            unique_together={
                (
                    "user",
                    "original_text",
                    "source_language",
                    "target_language",
                    "translator_service",
                )
            },
        ),
    ]
