# Generated by Django 5.2.1 on 2025-08-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reader", "0004_remove_translation_reader_tran_origina_8549e1_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="total_pages",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userbookprogress",
            name="last_read_page",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="prefered_background_color",
            field=models.CharField(default="light"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="prefered_font_size",
            field=models.IntegerField(default=16),
        ),
    ]
