# Generated by Django 5.2.1 on 2025-08-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reader", "0005_chapter_total_pages_userbookprogress_last_read_page_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="language",
            field=models.CharField(
                choices=[
                    ("ru", "ru"),
                    ("en", "en"),
                    ("de", "de"),
                    ("fr", "fr"),
                    ("es", "es"),
                    ("it", "it"),
                    ("pt", "pt"),
                    ("pl", "pl"),
                    ("nl", "nl"),
                    ("ja", "ja"),
                    ("zh", "zh"),
                    ("ko", "ko"),
                    ("ar", "ar"),
                    ("hi", "hi"),
                    ("tr", "tr"),
                    ("uk", "uk"),
                    ("bg", "bg"),
                    ("cs", "cs"),
                ],
                max_length=10,
            ),
        ),
    ]
