# Generated by Django 5.2.1 on 2025-08-03 14:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reader", "0007_alter_book_language"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="prefered_background_color",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="prefered_font_size",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="reading_font_size",
            field=models.IntegerField(
                default=16,
                validators=[
                    django.core.validators.MinLengthValidator(12),
                    django.core.validators.MaxLengthValidator(28),
                ],
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="reading_theme",
            field=models.CharField(
                choices=[("light", "Светлая"), ("sepia", "Сепия"), ("dark", "Темная")],
                default="light",
                max_length=10,
            ),
        ),
    ]
