# Generated by Django 5.2.1 on 2025-08-03 14:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reader", "0008_remove_userprofile_prefered_background_color_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="reading_font_size",
            field=models.IntegerField(
                default=16,
                validators=[
                    django.core.validators.MinValueValidator(12),
                    django.core.validators.MaxValueValidator(28),
                ],
            ),
        ),
    ]
