# Generated by Django 5.2.1 on 2025-08-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reader", "0009_alter_userprofile_reading_font_size"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="flashcard",
            options={"ordering": ["next_review"]},
        ),
        migrations.RemoveField(
            model_name="flashcard",
            name="status",
        ),
        migrations.AddField(
            model_name="flashcard",
            name="is_learning",
            field=models.BooleanField(
                default=True, help_text="Карточка на этапе первоначального изучения?"
            ),
        ),
        migrations.AddField(
            model_name="flashcard",
            name="learning_step",
            field=models.PositiveIntegerField(
                default=1, help_text="Карточка на этапе первоначального изучения?"
            ),
        ),
    ]
