# Generated by Django 5.2.1 on 2025-08-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reader", "0010_alter_flashcard_options_remove_flashcard_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="translation",
            name="alternatives",
            field=models.JSONField(
                blank=True,
                default=list,
                null=True,
                verbose_name="Альтернативные переводы",
            ),
        ),
        migrations.AlterField(
            model_name="translation",
            name="translator_service",
            field=models.CharField(
                choices=[
                    ("deepl", "DeepL"),
                    ("google", "Google Translate"),
                    ("microsoft", "Microsoft"),
                ],
                max_length=20,
                verbose_name="Сервис перевода",
            ),
        ),
    ]
