# Generated by Django 5.2.1 on 2025-08-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reader", "0011_translation_alternatives_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="translation",
            name="translator_service",
            field=models.CharField(
                choices=[
                    ("deepl", "DeepL"),
                    ("chatgpt", "ChatGPT"),
                    ("microsoft", "Microsoft"),
                ],
                max_length=20,
                verbose_name="Сервис перевода",
            ),
        ),
    ]
