# Generated by Django 5.2.1 on 2025-08-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reader", "0012_alter_translation_translator_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
