# Generated by Django 5.2.1 on 2025-08-15 14:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reader", "0013_alter_book_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="DictionaryCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("language", models.CharField(default="en", max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name="dictionaryentry",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dictionaryentry",
            name="definition",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="dictionaryentry",
            name="hits",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dictionaryentry",
            name="level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A1", "A1"),
                    ("A2", "A2"),
                    ("B1", "B1"),
                    ("B2", "B2"),
                    ("C1", "C1"),
                    ("C2", "C2"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dictionaryentry",
            name="raw",
            field=models.TextField(
                blank=True, help_text="Original raw text from source"
            ),
        ),
        migrations.AddField(
            model_name="dictionaryentry",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="dictionaryentry",
            name="transcription",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="dictionaryentry",
            name="word",
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AddField(
            model_name="dictionaryentry",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="entries", to="reader.dictionarycategory"
            ),
        ),
        migrations.RemoveField(
            model_name="dictionaryentry",
            name="language",
        ),
        migrations.RemoveField(
            model_name="dictionaryentry",
            name="translation",
        ),
        migrations.RemoveField(
            model_name="dictionaryentry",
            name="user",
        ),
        migrations.AlterUniqueTogether(
            name="dictionaryentry",
            unique_together={("word", "level")},
        ),
    ]
