# Generated by Django 5.2.1 on 2025-08-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reader", "0015_alter_book_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="language_to_learn",
            field=models.CharField(
                choices=[
                    ("ru", "Russian"),
                    ("en", "English"),
                    ("es", "Spanish"),
                    ("fr", "French"),
                    ("de", "German"),
                    ("zh", "Chinese"),
                    ("ja", "Japanese"),
                    ("id", "Indonesian"),
                ],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="native_language",
            field=models.CharField(
                choices=[
                    ("ru", "Russian"),
                    ("en", "English"),
                    ("es", "Spanish"),
                    ("fr", "French"),
                    ("de", "German"),
                    ("zh", "Chinese"),
                    ("ja", "Japanese"),
                    ("id", "Indonesian"),
                ],
                max_length=2,
            ),
        ),
    ]
