# Generated by Django 5.2.1 on 2026-07-27 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reader", "0017_remove_userprofile_avatar_url_userprofile_avatar_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="mode",
            field=models.CharField(
                choices=[
                    ("default", "General Tutor"),
                    ("grammar", "Grammar Lab"),
                    ("roleplay", "Role Play"),
                    ("conversation", "Conversation Club"),
                    ("writing", "Writing Coach"),
                    ("vocabulary", "Vocabulary Builder"),
                ],
                default="default",
                max_length=30,
            ),
        ),
    ]
