from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reader", "0020_new_value_for_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="WordAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lemma",
                    models.CharField(
                        blank=True,
                        max_length=255,
                    ),
                ),
                (
                    "ipa",
                    models.CharField(
                        blank=True,
                        max_length=255,
                    ),
                ),
                (
                    "part_of_speech",
                    models.CharField(
                        blank=True,
                        max_length=50,
                    ),
                ),
                (
                    "grammar",
                    models.JSONField(
                        blank=True,
                        default=dict,
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True,
                    ),
                ),
                (
                    "synonyms",
                    models.JSONField(
                        blank=True,
                        default=list,
                    ),
                ),
                (
                    "examples",
                    models.JSONField(
                        blank=True,
                        default=list,
                    ),
                ),
                (
                    "etymology",
                    models.TextField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                    ),
                ),
                (
                    "translation",
                    models.OneToOneField(
                        on_delete=models.CASCADE,
                        related_name="word_analysis",
                        to="reader.translation",
                    ),
                ),
            ],
        ),
    ]